name: CI

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Install chrome
        run: |
          sudo apt update && sudo apt install curl -y
          curl http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_148.0.7778.167-1_amd64.deb \
            -o /tmp/google-chrome-stable_current_amd64.deb
          sudo DEBIAN_FRONTEND=noninteractive \
            apt install /tmp/google-chrome-stable_current_amd64.deb -y --allow-downgrades

      - name: Executar testes
        run: npm test

        
      - name: Iniciar aplicação
        run: npm start &  